language: node_js
node_js:
  - "6"
  - "7"
env:
  global:
    - SKIP_IPV6=true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2e2424552603592e8e34
    on_success: change
    on_failure: always
    on_start: never
